version: '3'

services:
  flask-app:
    build:
      context: ./kafkaProducer
      dockerfile: Dockerfile
    container_name: kafkaProducer
    ports:
      - "5000:5000"  # Map container's port 5000 to host's port 5000
    networks:
      - my-network

  opcua-reader:
    build:
      context: ./readOpcData
      dockerfile: Dockerfile
    container_name: readOpcData
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
